# Generated by Django 3.2.8 on 2021-12-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gstn', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('IsSupplier', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Hsnid', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('HsnCode', models.IntegerField(primary_key=True, serialize=False)),
                ('Tax', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartyId', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Date', models.DateField()),
                ('ProductId', models.IntegerField()),
                ('Type', models.TextField()),
            ],
        ),
    ]
